#ifndef NETWORK_SYNCHRONIZER_TESTS_NETSYNC_TESTS_H
#define NETWORK_SYNCHRONIZER_TESTS_NETSYNC_TESTS_H
#ifdef CATCH_TESTS
#include "network_synchronizer/bit_array_test.h"
#endif // CATCH_TESTS
#endif // NETWORK_SYNCHRONIZER_TESTS_NETSYNC_TESTS_H
